# This is a basic workflow that is manually triggered

name: CI/CD Pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [
  push,
  pull_request
]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: 54.209.2.134
          username: ec2-user
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            nvm use 16.20
            cd dash3
            git stash
            git pull
            npm install --force
            ng build --configuration production
            sudo cp -r dist/login-demo/* /usr/share/nginx/html
            echo "moved file"
            sudo systemctl restart nginx
            echo "restarted nginx"
            
